
/****** Script for SelectTopNRows command from SSMS  ******/

CREATE VIEW [app].[vSchedule]
AS
SELECT [Id]
      ,[EngagementFk]
      ,[Principal]
      ,[DateFrom]
      ,[DateTo]
      ,[TripDirector]
      ,[SpeechWriter]
      ,[CommunicationsLead]
      ,[BriefDueToGCEByDate]
      ,[BriefDueToBGC3ByDate]
      ,[ScheduleComment]
      ,[ScheduleCommentRtf]
      ,[ScheduledBy]
      ,[ScheduledDate]
      ,[ApproveDecline]
      ,[ReviewComment]
      ,[ReviewCommentRtf]
      ,[ReviewCompletedBy]
      ,[ReviewCompletedDate]
      ,[LeaderFk]
      ,[TripDirectorFk]
      ,[SpeechWriterFk]
      ,[CommunicationsLeadFk]
      ,[ScheduledByFk]
      ,[ReviewCompletedByFk]
  FROM [dbo].[vSchedule]