
kind: pipeline
type: docker
name: Pull Request Checker

steps:

# - name: Get Web Build Tools
  # image: mcr.microsoft.com/dotnet/core/sdk:3.1
  # commands:
  # - export PATH="$PATH:/root/.dotnet/tools"
 
- name: Run Package Manager
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    commands:    
    - npm intall
 
- name: Clean Project
   image: mcr.microsoft.com/dotnet/core/sdk:3.1
   commands:
    - dotnet clean sample/InvestmentScore.SPA/InvestmentScore.Spa.sln

- name: Build Project
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - dotnet --list-sdks
  - dotnet build sample/InvestmentScore.SPA/InvestmentScore.Spa.sln

trigger:
  branch:
      - gitlearning
  event:
    include:
      - push
