## Building up yml file for build

kind: pipeline
type: docker
name: Pull Request Checker

steps:

- name: Get Web Build Tools
  image: mcr.microsoft.com/dotnet/core/sdk
  commands:
  - export PATH="$PATH:/root/.dotnet/tools"
  - mkdir -p /usr/share/dotnet/sdk/3.1.408/Microsoft/VisualStudio/v16.0/WebApplications
  - cp buildtools/Microsoft.WebApplication.targets /usr/share/dotnet/sdk/3.1.408/Microsoft/VisualStudio/v16.0/WebApplications
  - dotnet add LEAD/Scheduler/Scheduler.csproj package NuGet.Frameworks --version 4.5.2
  # - dotnet tool install -g Microsoft.VisualStudio.Workload.WebBuildTools

# - name: Clean Project
  # image: mcr.microsoft.com/dotnet/sdk
  # commands:
  # - mkdir -p /usr/share/dotnet/sdk/5.0.202/Microsoft/VisualStudio/v16.0/WebApplications
  # - cp buildtools/Microsoft.WebApplication.targets /usr/share/dotnet/sdk/5.0.202/Microsoft/VisualStudio/v16.0/WebApplications
  # - dotnet clean LEAD/Scheduler/Scheduler.csproj

# - name: Build Project
  # image: mcr.microsoft.com/dotnet/sdk
  # commands:
  # - mkdir -p /usr/share/dotnet/sdk/5.0.202/Microsoft/VisualStudio/v16.0/WebApplications
  # - cp buildtools/Microsoft.WebApplication.targets /usr/share/dotnet/sdk/5.0.202/Microsoft/VisualStudio/v16.0/WebApplications
  # - ls -l /usr/share/dotnet/sdk/5.0.202
  # - dotnet restore LEAD/Scheduler/Scheduler.csproj
  # - dotnet build LEAD/Scheduler/Scheduler.csproj


trigger:
  branch:
      - gitlearning
  event:
    include:
      - pull_request
      - push
