## Building up yml file for build

kind: pipeline
type: exec
name: LEAD Solution Build

platform:
  os: windows
  arch: amd64

clone:
    disable: true

platform:
  os: windows
  arch: amd64


steps:     
 - name: Remove Workspace COntents Subfolders
   failure: ignore
   commands:
     - Start-Process powershell -Verb runAs
     - Remove-Item -path 'D:\Repos\master\*' -Recurse -Force -EA SilentlyContinue
       
  
 - name: Clone Lead Project
   commands:
     - D:
     - cd \Repos\master
     - git clone https://github.com/josem-bmgf/master.git
     - cd \master
     - git checkout gitlearning
         
 - name: Start Project build
   failure: ignore
   commands:
     #- Powershell.exe -File C:\DH2-CI\S-BI-Agile-DH2\BuildAndDeploy\Build\BuildSolution.ps1
     - Powershell.exe -Comamnd  buildSolution "master\LEAD\Scheduler.sln"
     
  
 - name: Stop Existing Powershell Process
   failure: ignore
   commands:
     - taskkill /F /IM powershell.exe

      
     
node:
  keyA: myBuild
    
    
trigger:
  branch:
    include:
    - gitlearning