## Yml file for build

kind: pipeline
type: docker
name: Project Build Pull Request Checker

steps:
  
 - name: clean
   image: mcr.microsoft.com/dotnet/sdk:latest
   commands:
   - mkdir -p /usr/share/dotnet/sdk/5.0.301/Microsoft/VisualStudio/v11.0/SSDT
   - cp DB/IPM_Valuation_Database.build/Microsoft.Data.Tools.Schema.SqlTasks.targets /usr/share/dotnet/sdk/5.0.301/Microsoft/VisualStudio/v11.0/SSDT/
   - dotnet clean DB/IPM_Valuation_Database.sln

 - name: build
   image: mcr.microsoft.com/dotnet/core/sdk:latest
   commands:
   - mkdir -p /usr/share/dotnet/sdk/5.0.301/Microsoft/VisualStudio/v11.0/SSDT
   - cp DB/IPM_Valuation_Database.build/Microsoft.Data.Tools.Schema.SqlTasks.targets /usr/share/dotnet/sdk/5.0.301/Microsoft/VisualStudio/v11.0/SSDT/
   - cp DB/IPM_Valuation_Database.build/dotnet.dll /usr/share/dotnet/sdk/5.0.301/
   - dotnet build DB/IPM_Valuation_Database.sln

trigger:
    branch:
    include:
    - again
    event:
    include:
    - push

# ---

# kind: pipeline
# type: docker
# name: Project Build and SQL Deploy

# steps:    
  # - name: clean
    # image: mcr.microsoft.com/dotnet/sdk:latest
    # commands:
      # - dotnet clean CDE_Operations/CDE_Operations.sln


  # - name: build
    # image: mcr.microsoft.com/dotnet/core/sdk:latest
    # commands:
      # - dotnet build CDE_Operations/CDE_Operations.sln


  # - name: Deploy to Azure SQL Database 
    # image: sijaymm/sqlpackage
    # environment:
      # SERVER_NAME:
        # from_secret: SERVER_NAME
      # DB_NAME:
        # from_secret: DB_NAME
      # USERNAME:
        # from_secret: USERNAME
      # PASSWORD:
        # from_secret: PASSWORD
    # commands:
      # - sqlpackage /a:Publish /p:VerifyDeployment=True /p:CommandTimeout=0 /p:DatabaseServiceObjective=P2 /p:AllowIncompatiblePlatform=True /tsn:tcp:$SERVER_NAME /tdn:$DB_NAME /tu:$USERNAME /tp:$PASSWORD /sf:/drone/src/CDE_Operations/CDE_Operations.Database.build/bin/Debug/netstandard2.0/CDE_Operations.Database.build.dacpac
