kind: pipeline
type: docker
name: Build Project

steps:    
- name: clean solution
  image: mcr.microsoft.com/dotnet/sdk:latest
  commands:
    - cp -r BuildTools/. /drone
    - ls -l /drone
    - dotnet clean myWeb/myWeb.csproj

- name: build project
  image: mcr.microsoft.com/dotnet/sdk:latest
  commands:
   - cp -r BuildTools/. /drone
   - ls /drone
   - dotnet --version
   # - dotnet restore myWeb/myWeb.csproj
   # - dotnet build myWeb/myWeb.csproj
   - echo ${DRONE_BUILD_NUMBER}
   - echo ${VERSION_TAG}
 
trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
