
kind: pipeline
type: docker
name: Pull Request Checker

steps:

# - name: Get Web Build Tools
  # image: mcr.microsoft.com/dotnet/core/sdk:3.1
  # commands:
  # - export PATH="$PATH:/root/.dotnet/tools"
 
- name: Run Package Manager
  image: mcr.microsoft.com/dotnet/core/sdk:3.1   #node:latest  
  commands:
  - apt-get update
  - apt-get -y install nodejs
  - apt-get -y install npm
  - cd sample/InvestmentScore.SPA/
  - npm install
  
- name: Clean Project
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
   - dotnet clean sample/InvestmentScore.SPA/InvestmentScore.Spa.csproj

- name: Build Project
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - dotnet build sample/InvestmentScore.SPA/InvestmentScore.Spa.csproj
  - ls sample/InvestmentScore.SPA/obj/Debug
 
- name: Publish
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install zip unzip -y
  - apt-get -y install npm
  - dotnet publish --configuration Debug sample/InvestmentScore.SPA/InvestmentScore.Spa.csproj --output /drone/src/web/
  - cd /drone/src/web
  - zip -r webfile.zip *
  - cp -r webfile.zip /drone/src
  
- name: Deploy
  image: mcr.microsoft.com/azure-cli
  environment:
    spn:
     from_secret: client_id
    pass:
     from_secret: client_password
    tenant:
     from_secret: client_tenant
    app_web:
     from_secret: app_web_name
    web_rg:
     from_secret: app_web_rg
  commands:
  - az login --service-principal -u $spn -p $pass --tenant $tenant
  - az webapp deployment source config-zip --src /drone/src/webfile.zip -n $app_web -g $web_rg
 
trigger:
  branch:
      - gitlearning
  event:
    include:
      - push
