
kind: pipeline
type: docker
name: Pull Request Checker

steps:

# - name: Get Web Build Tools
  # image: mcr.microsoft.com/dotnet/core/sdk:3.1
  # commands:
  # - export PATH="$PATH:/root/.dotnet/tools"
 
- name: Run Package Manager
  image: node:latest  #   mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - cd sample/InvestmentScore.SPA/
  - npm install
  
- name: Clean Project
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
   - dotnet clean sample/InvestmentScore.SPA/InvestmentScore.Spa.csproj

- name: Build Project
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - dotnet --list-sdks
  - dotnet build sample/InvestmentScore.SPA/InvestmentScore.Spa.csproj
  - ls sample/InvestmentScore.SPA/obj/
 
- name: Publish
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  commands:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install zip unzip -y
  - dotnet publish --configuration Release InvestmentScore.Spa.csproj --output /drone/src/web/
  - cd /drone/src/web
  - zip -r webfile.zip *
  - cp -r webfile.zip /drone/src
  
- name: deploy
  image: mcr.microsoft.com/azure-cli
  environment:
   # id:
    # from_secret: client_id
   # pass:
    # from_secret: client_password
   # tenant:
    # from_secret: client_tenant
   # app_web_name:
    # from_secret: app_web_name
   # app_web_rg:
    # from_secret: app_web_rg
    - $id = "dedc9ec9-0d1f-46b2-bf3e-5cc525a34254"
    - $key = "xS-sR.k4v0-S7ZhItCN4HW6o20_JDR9nr_"
    - $tenant = "365fdb25-c77e-4884-b5fa-6c38cc236c83"
    - $app_web_name = "nostradini"
    - $app_web_rg = "Default-Web-SoutheastAsia"
  commands:
  - az login --service-principal -u $id -p $key --tenant $tenant
  - az webapp deployment source config-zip --src /drone/src/webfile.zip -n $app_web_name -g $app_web_rg
 
trigger:
  branch:
      - gitlearning
  event:
    include:
      - push
