kind: pipeline
type: docker
name: Build Project

steps:    
  - name: clean
    image: mcr.microsoft.com/dotnet/sdk:latest
    commands:
      - cp Microsoft.WebApplication.targets /drone
      - dotnet clean myWeb/myWeb.csproj

  - name: build
    commands:
    ls /drone
     - dotnet build myWeb/myWeb.csproj
 
 trigger: 
 branch: 
  - master
 event:
    include:
      - push
