kind: pipeline
type: docker
name: Build Project

steps:    
- name: clean solution
  image: mcr.microsoft.com/dotnet/sdk:latest
  commands:
    - cp BuildTools/. /drone
    - ls -l /drone
    - dotnet clean myWeb/myWeb.csproj

- name: build project
  image: mcr.microsoft.com/dotnet/sdk:latest
  commands:
   - cp BuildTools/. /drone
   - ls /drone
   - dotnet --version
   - dotnet restore myWeb/myWeb.csproj
   #- dotnet build myWeb/myWeb.csproj
 
trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
