CREATE TABLE [dbo].[ErrorLog] (
    [LogID] [int] IDENTITY(1,1) NOT NULL,
	[RunDate] [datetime] NOT NULL,
	[UserID] [int] NOT NULL,
	[Details] [nvarchar](MAX) NULL,
	 CONSTRAINT [PK_ErrorLog] PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[ErrorLog]  WITH NOCHECK ADD  CONSTRAINT [FK_ErrorLog_SysUser] FOREIGN KEY([UserID])
REFERENCES [dbo].[SysUser] ([Id])
GO