CREATE TABLE [gdx].[measure_dimension](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[measure_nm] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
