//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Principal
    {
        public int Id { get; set; }
        public int EngagementFK { get; set; }
        public int LeaderFK { get; set; }
        public int TypeFK { get; set; }
    
        public virtual Leader Leader { get; set; }
        public virtual PrincipalType PrincipalType { get; set; }
        public virtual Engagement Engagement { get; set; }
    }
}
