//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysGroupUserPrivilege
    {
        public int Id { get; set; }
        public int SysGroupFK { get; set; }
        public int SysUserFK { get; set; }
        public bool SysAdmin { get; set; }
        public bool AppAdmin { get; set; }
        public bool GroupAdmin { get; set; }
        public bool GroupEntry { get; set; }
        public bool GroupApprover { get; set; }
        public bool Scheduler { get; set; }
        public bool ScheduleApprover { get; set; }
        public bool BlackOutDateEntry { get; set; }
        public bool Status { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EntryByFk { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedByFk { get; set; }
    
        public virtual SysGroup SysGroup { get; set; }
        public virtual SysUser SysUser { get; set; }
        public virtual SysUser SysUser1 { get; set; }
        public virtual SysUser SysUser2 { get; set; }
    }
}
