//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEngagementLeaderSchedule
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public string DetailsRtf { get; set; }
        public string Objectives { get; set; }
        public string ObjectivesRtf { get; set; }
        public string PrincipalRequired { get; set; }
        public string PrincipalAlternate { get; set; }
        public string ExecutiveSponsor { get; set; }
        public string Visibility { get; set; }
        public string EngagementType { get; set; }
        public string EngagementExtInt { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string Purpose { get; set; }
        public string BriefOwner { get; set; }
        public string Staff { get; set; }
        public string Duration { get; set; }
        public int DurationInMinutes { get; set; }
        public int DurationInDays { get; set; }
        public string DateFlexible { get; set; }
        public string YearQuarter { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string TeamInfo { get; set; }
        public string Division { get; set; }
        public string DivisionDescription { get; set; }
        public string Team { get; set; }
        public string StrategicPriority { get; set; }
        public string TeamRanking { get; set; }
        public string PresidentRanking { get; set; }
        public string PresidentComment { get; set; }
        public string PresidentCommentRtf { get; set; }
        public string Status { get; set; }
        public int StatusDisplaySortSequence { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string EntryBY { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ScheduleFromDate { get; set; }
        public Nullable<System.DateTime> ScheduleToDate { get; set; }
        public string TripDirector { get; set; }
        public string SpeechWriter { get; set; }
        public string CommunicationsLead { get; set; }
        public Nullable<System.DateTime> ScheduleBriefDueToGCEByDate { get; set; }
        public Nullable<System.DateTime> ScheduleBriefDueToBGC3ByDate { get; set; }
        public string ScheduleComment { get; set; }
        public string ScheduleCommentRtf { get; set; }
        public string ScheduledBy { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string ScheduleApprovalStatus { get; set; }
        public string ScheduleReviewComment { get; set; }
        public string ScheduleReviewCommentRtf { get; set; }
        public string ScheduleReviewCompletedBy { get; set; }
        public Nullable<System.DateTime> ScheduleReviewCompletedDate { get; set; }
        public string LeaderFirstName { get; set; }
        public string LeaderLastName { get; set; }
        public string LeaderShortName { get; set; }
        public string LeaderADUser { get; set; }
        public bool IsConfidential { get; set; }
        public bool IsExternal { get; set; }
        public bool EntryCompleted { get; set; }
        public bool PresidentReviewCompleted { get; set; }
        public bool ScheduleCompleted { get; set; }
        public bool ScheduleReviewCompleted { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    }
}
