INSERT INTO #metadata_columns VALUES 
('gdx',		'gdx',	'vw_country_dimension',				'country_dimension',				'iso_country_cd',					'iso_country_cd',					1),

('staging', 'gdx',	'measure_dimension',				'measure_dimension',				'measure_nm',						'measure_nm',						1),

('staging', 'gdx',	'gates_data_exchange_metadata',		'gates_data_exchange_metadata',		'gdx_dataset_id',					'gdx_dataset_id',					1),
('staging', 'gdx',	'gates_data_exchange_metadata',		'gates_data_exchange_metadata',		'gdx_resource_id',					'gdx_resource_id',					1),

('staging', 'gdx',	'measure_format_dimension',			'measure_format_dimension',			'measure_format_nm',				'measure_format_nm',				1),

('staging', 'gdx',    'ihme_attributable_fraction',          'ihme_attributable_fraction',            'ihme_cause_id',                    'ihme_cause_id',                    1),
('staging', 'gdx',    'ihme_attributable_fraction',          'ihme_attributable_fraction',            'cause_nm',                            'cause_nm',                            1),
('staging', 'gdx',    'ihme_attributable_fraction',          'ihme_attributable_fraction',            'disease_nm',                        'disease_nm',                        1),
('staging', 'gdx',    'ihme_attributable_fraction',          'ihme_attributable_fraction',            'age_nr',                            'age_nr',                            1),

('gdx',		'gdx',	'vw_cause_dimension',				'cause_dimension',					'ihme_cause_id',					'ihme_cause_id',					1),

('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'age_nr',							'age_nr',							1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_population',				'ihme_population',					'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'age_nr',							'age_nr',							1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_united_nations_population',		'united_nations_population',		'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'ihme_cause_id',					'ihme_cause_id',					1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'attributable_cause_nm',			'attributable_cause_nm',			1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'variable_nm',						'variable_nm',						1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'disease_burden_source_nm',			'disease_burden_source_nm',			1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'age_nr',							'age_nr',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'scenario',							'scenario',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_disease_burden',			'ihme_disease_burden',				'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'ihme_cause_id',					'ihme_cause_id',					1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'attributable_cause_nm',			'attributable_cause_nm',			1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'variable_nm',						'variable_nm',						1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'disease_burden_source_nm',			'disease_burden_source_nm',			1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'age_nr',							'age_nr',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'scenario',							'scenario',							1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_disease_burden_attributable',			'ihme_disease_burden',				'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'proxy_nm',							'proxy_nm',							1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'variable_nm',						'variable_nm',						1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_ihme_vaccine_coverage',				'ihme_vaccine_coverage',					'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'proxy_nm',							'proxy_nm',							1),
('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'variable_nm',						'variable_nm',						1),
('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_who_vaccine_coverage',				'who_vaccine_coverage',					'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'age_nr',							'age_nr',							1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'measure_format_dimension_id',		'measure_format_dimension_id',		1),
('gdx',		'gdx',	'vw_health_adjusted_life_expectancy',		'health_adjusted_life_expectancy',		'variable_nm',						'variable_nm',						1),

('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'measure_format_dimension_id',		'measure_format_dimension_id',		1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'cause_id',							'cause_id',							1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'attributable_cause_nm',			'attributable_cause_nm',			1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'proxy_nm',							'proxy_nm',			1),
('gdx',		'gdx',	'vw_dropdown_scope',						'dropdown_scope',						'variable_nm',						'variable_nm',			1),

('gdx',		'gdx',	'vw_united_nations_birth_rates',		'united_nations_birth_rates',		'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_united_nations_birth_rates',		'united_nations_birth_rates',		'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_united_nations_birth_rates',		'united_nations_birth_rates',		'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_united_nations_birth_rates',		'united_nations_birth_rates',		'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_united_nations_birth_rates',		'united_nations_birth_rates',		'measure_format_dimension_id',		'measure_format_dimension_id',		1),

('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'country_dimension_id',				'country_dimension_id',				1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'sex_nm',							'sex_nm',							1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'gates_data_exchange_metadata_id',	'gates_data_exchange_metadata_id',	1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'age_group_nm',						'age_group_nm',						1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'age_nr',							'age_nr',							1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'year_nr',							'year_nr',							1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'measure_dimension_id',				'measure_dimension_id',				1),
('gdx',		'gdx',	'vw_united_nations_pregnant_population',		'united_nations_pregnant_population',		'measure_format_dimension_id',		'measure_format_dimension_id',		1)

