CREATE TABLE [hst].[Schedule] (
    [Id]                   INT           IDENTITY (1000000, 1) NOT NULL,
    [IdFk]                 INT           NULL,
    [EngagementFk]         INT           NULL,
    [LeaderFk]             INT           NULL,
    [DateFrom]             DATETIME      NULL,
    [DateTo]               DATETIME      NULL,
    [TripDirectorFk]       INT           NULL,
    [SpeechWriterFk]       INT           NULL,
    [CommunicationsLeadFk] INT           NULL,
    [BriefDueToGCEByDate]  DATETIME      NULL,
    [BriefDueToBGC3ByDate] DATETIME      NULL,
    [ScheduleComment]      VARCHAR (MAX) NULL,
    [ScheduleCommentRtf]   VARCHAR (MAX) NULL,
    [ScheduledByFk]        INT           NULL,
    [ScheduledDate]        DATETIME      NULL,
    [ApproveDecline]       CHAR (1)      NULL,
    [ReviewComment]        VARCHAR (MAX) NULL,
    [ReviewCommentRtf]     VARCHAR (MAX) NULL,
    [ReviewCompletedByFk]  INT           NULL,
    [ReviewCompletedDate]  DATETIME      NULL,
    [IsDeleted]            BIT           NULL,
    CONSTRAINT [PK_ScheduleHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

